### ISSUE TITLE
Position multiplying after skin reload

### ISSUE THREAD

**Issue by KrazyManJ** [keifufu/WebNowPlaying-Redux-Rainmeter#5] opened 2023-06-24 11:43 UTC
So i am currently working on widget to take control over web music player (mainly spotify) with your plugin and after each reload it multiply position parameter e.g. I reload it 5 times and instead of adding one second in position, it adds 5 seconds, 10 times reload adds 10 seconds each seconds and so on.

You can check out code of widget [here](https://github.com/KrazyManJ/rainmeter-dynamic-island/blob/main/Music.ini).

Also i am using the newest version of Rainmeter (4.5.17.3700) (64-bit) and the newest version of this plugin (I've downloaded it yesterday).

**Comment by keifufu** [comment] 2023-06-24 11:48
That sounds like it might only be possible if you use the spotify desktop player. Are you sure you're using the web version of spotify and don't have the desktop player open or anything? You can check which player it's grabbing info from with `PlayerType=Player`, where Spotify is the website and "Windows Media Session" is Spotify Desktop

**Comment by KrazyManJ** [comment] 2023-06-24 12:43
No, i am sure that i am using spotify version installed by executable and not by windows store, also i've done configuration of spotify to work with this extension via [this tutorial by author of monstercat visualizer](https://github.com/marcopixel/monstercat-visualizer/wiki/WebNowPlaying-Spotify).

**Comment by keifufu** [comment] 2023-06-24 12:45
You had mentioned "web music player (mainly spotify)", so I thought you'd be using the website.
It doesn't matter if you have the executable or microsoft store version installed.
Please uninstall spicetify as It's no longer needed with WebNowPlaying 2.0.0 and newer and it could be the cause of the issue.

**Comment by KrazyManJ** [comment] 2023-06-24 12:52
So now i can use default spotify app without spicetify and all my functionality in widget posted above should be fully compatible to gather all info by your plugin? I am asking just to be sure because that spicetify configuration took me long time to do.

**Comment by keifufu** [comment] 2023-06-24 12:54
As long as you're on windows 10 or 11, yes.

**Comment by KrazyManJ** [comment] 2023-06-24 13:06
After proper uninstallation of spotify + spicetify and installing it back without spicetify it still does the same problem, still after skin reload it multiplies progress based on count of reload.

**Comment by keifufu** [comment] 2023-06-24 13:08
Do you have any other skins loaded? Do you reload all skins or just the music skin?

**Comment by KrazyManJ** [comment] 2023-06-24 13:11
I am just reloading `Music.ini` skin and it is only skin i have currently on my screen. I am refreshing it via button with label "Refresh" that i can press only when i select specific skin so i assume it refreshes only that selected skin.

**Comment by keifufu** [comment] 2023-06-24 13:18
Please give this version of the plugin a go, replace WebNowPlaying.dll in `%LocalAppData%\Rainmeter\Plugins` with the .dll in the zip: [WebNowPlaying.zip](https://github.com/keifufu/WebNowPlaying-Redux-Rainmeter/files/11857051/WebNowPlaying.zip)

**Comment by KrazyManJ** [comment] 2023-06-24 13:25
Problem solved! I guess you've modified locally your plugin and send me copy to test it. After few tries (even hard-click spamming just to test it) it does not multiply progress anymore 😁 Thank you for your quick response and solving this issue, love this plugin cuz it turns dream of making apple-like widgets come true! ❤️ Keep it up!

**Comment by keifufu** [comment] 2023-06-24 13:26
Glad it worked!
I actually made this to fix another users problem on the rainmeter forums. It was already committed in 35c1e22cd822450f4d6a792db56c5d2447e50fa3 but I have yet to make a release for it.

**Closed by keifufu** 2023-06-24 13:26 UTC

**Comment by keifufu** [comment] 2023-06-24 13:35
Just published [v2.0.4](https://github.com/keifufu/WebNowPlaying-Redux-Rainmeter/releases/tag/2.0.4) if you want the version bump
